---
title: "Oliver Twist"
author: "Adejumo Ridwan Suleiman"
date: "`r Sys.Date()`"
output: html_document
---

## Project Gutenberg

## libraries 
```{r}
library(dplyr) #data manipulation
library(purrr) #functional programming
library(tidytext) #text mining
library(gutenbergr) #project gutenberg package
library(ggplot2) #data visualization
```

# Load the novel Oliver Twist
```{r}
# Check for book id
gutenberg_metadata %>% 
  filter(title == "Oliver Twist")

# create book data
oliver_twist <- gutenberg_download(730)
```


# Unnest token and stopword removal
```{r}
tidy_oliver_twist <- oliver_twist %>% 
  unnest_tokens(word, text) %>% 
  anti_join(stop_words)

tidy_oliver_twist
```

# Word Frequency
```{r}
tidy_oliver_twist %>% 
  count(word, sort = TRUE)
```

# Word Frequency visualization
```{r}
tidy_oliver_twist %>% 
  count(word, sort = TRUE) %>% 
  filter(n > 200) %>%
  top_n(10) %>% 
  ggplot(aes(reorder(word, n),n,fill = word)) +
  geom_col() +
  coord_flip() +
  labs(y = NULL, x = "word", title = "The Most Common Words in Oliver Twist")
```

# Sentiment Analysis(using bing)
- Bing categorizes words into negative and positive categories
```{r}
bing_word_counts <- tidy_oliver_twist %>%
  inner_join(get_sentiments("bing")) %>%
  count(word, sentiment, sort = TRUE) 

bing_word_counts
```

